import { SeedQuestion } from './seed-questions';

const TRIVIA_TIME_LIMIT_SECONDS = 10;
const CORRECT_POINTS = 3;

function trivia(
  order: number,
  text: string,
  textHi: string,
  options: [string, string, string, string],
  optionsHi: [string, string, string, string],
  correctIndex: 0 | 1 | 2 | 3,
): SeedQuestion {
  const keys = ['A', 'B', 'C', 'D'] as const;
  return {
    text,
    textHi,
    order,
    timeLimitSeconds: TRIVIA_TIME_LIMIT_SECONDS,
    type: 'trivia',
    options: options.map((text, i) => ({
      key: keys[i],
      text,
      textHi: optionsHi[i],
      points: i === correctIndex ? CORRECT_POINTS : 0,
    })),
  };
}

export const TRIVIA_QUESTIONS: SeedQuestion[] = [
  // Set A — Guess the Founder's App
  trivia(
    1,
    'Nikhil Kamath earns his fortune mainly through this app:',
    'निखिल कामथ की मुख्य कमाई इस ऐप से होती है:',
    ['PhonePe', 'Kite (Zerodha)', 'Paytm', 'Groww'],
    ['PhonePe', 'Kite (Zerodha)', 'Paytm', 'Groww'],
    1,
  ),
  trivia(
    2,
    "Vijay Shekhar Sharma built India's mobile-wallet-to-super-app story with:",
    'विजय शेखर शर्मा ने भारत की मोबाइल-वॉलेट-से-सुपर-ऐप कहानी किस ऐप से बनाई:',
    ['PhonePe', 'Paytm', 'Mobikwik', 'Freecharge'],
    ['PhonePe', 'Paytm', 'Mobikwik', 'Freecharge'],
    1,
  ),
  trivia(
    3,
    'Ritesh Agarwal turned budget hotels into a tech brand with:',
    'रितेश अग्रवाल ने बजट होटलों को टेक ब्रांड में किस ऐप से बदला:',
    ['MakeMyTrip', 'OYO', 'Airbnb India', 'Treebo'],
    ['MakeMyTrip', 'OYO', 'Airbnb India', 'Treebo'],
    1,
  ),
  trivia(
    4,
    'Falguni Nayar left investment banking to build:',
    'फाल्गुनी नायर ने इन्वेस्टमेंट बैंकिंग छोड़कर क्या बनाया:',
    ['Myntra', 'Nykaa', 'Purplle', 'Ajio'],
    ['Myntra', 'Nykaa', 'Purplle', 'Ajio'],
    1,
  ),
  trivia(
    5,
    'Deepinder Goyal turned a menu-scanning idea into:',
    'दीपिंदर गोयल ने मेन्यू-स्कैनिंग आइडिया को किसमें बदला:',
    ['Swiggy', 'Zomato', 'EatSure', 'FoodPanda'],
    ['Swiggy', 'Zomato', 'EatSure', 'FoodPanda'],
    1,
  ),
  trivia(
    6,
    'Bhavish Aggarwal disrupted city travel in India with:',
    'भाविश अग्रवाल ने भारत में शहरी यात्रा को किस ऐप से बदल डाला:',
    ['Uber', 'Ola', 'Rapido', 'Meru'],
    ['Uber', 'Ola', 'Rapido', 'Meru'],
    1,
  ),
  trivia(
    7,
    'Kunal Shah turned "pay your credit card bill on time" into a brand:',
    'कुणाल शाह ने "समय पर क्रेडिट कार्ड बिल भरो" को एक ब्रांड में बदला:',
    ['Slice', 'CRED', 'LazyPay', 'OneCard'],
    ['Slice', 'CRED', 'LazyPay', 'OneCard'],
    1,
  ),
  trivia(
    8,
    "Sameer Nigam built one of India's most-used UPI apps:",
    'समीर निगम ने भारत के सबसे ज़्यादा इस्तेमाल होने वाले UPI ऐप्स में से एक बनाया:',
    ['Google Pay', 'PhonePe', 'Amazon Pay', 'BHIM'],
    ['Google Pay', 'PhonePe', 'Amazon Pay', 'BHIM'],
    1,
  ),
  trivia(
    9,
    'Sridhar Vembu quietly built a global SaaS company from Tamil Nadu:',
    'श्रीधर वेम्बु ने तमिलनाडु से चुपचाप एक ग्लोबल SaaS कंपनी बनाई:',
    ['Freshworks', 'Zoho', 'Chargebee', 'Postman'],
    ['Freshworks', 'Zoho', 'Chargebee', 'Postman'],
    1,
  ),
  trivia(
    10,
    'Peyush Bansal made eyewear shopping digital-first with:',
    'पीयूष बंसल ने चश्मों की खरीदारी को डिजिटल-फर्स्ट किस ऐप से बनाया:',
    ['Titan Eye+', 'Lenskart', 'Specsmakers', 'GKB Opticals'],
    ['Titan Eye+', 'Lenskart', 'Specsmakers', 'GKB Opticals'],
    1,
  ),

  // Set B — Myth or Fact (Tech Adoption Lessons)
  trivia(
    11,
    "DMart's own app, DMart Ready, currently:",
    'DMart का अपना ऐप, DMart Ready, फिलहाल:',
    [
      'Earns more than its stores',
      'Is still running at a loss',
      'Was shut down',
      "Is DMart's #1 revenue driver",
    ],
    [
      'अपने स्टोर्स से ज़्यादा कमाता है',
      'अभी भी घाटे में चल रहा है',
      'बंद कर दिया गया',
      'DMart का #1 रेवेन्यू सोर्स है',
    ],
    1,
  ),
  trivia(
    12,
    'Zerodha became one of the most profitable brokers in India without ever:',
    'Zerodha भारत के सबसे मुनाफे वाले ब्रोकरों में से एक बना, बिना कभी:',
    [
      'Hiring engineers',
      'Raising outside funding',
      'Charging any fee',
      'Opening an office',
    ],
    ['इंजीनियर हायर किए', 'बाहरी फंडिंग लिए', 'कोई फीस लिए', 'ऑफिस खोले'],
    1,
  ),
  trivia(
    13,
    'Khatabook mainly replaced this for kirana shop owners:',
    'Khatabook ने किराना दुकानदारों के लिए मुख्य रूप से किसकी जगह ली:',
    [
      'Their shop signage',
      'Paper ledgers (bahi-khata)',
      'Their cash counter',
      'Their supplier contacts',
    ],
    [
      'उनकी दुकान का बोर्ड',
      'कागज़ की बही-खाता',
      'उनका कैश काउंटर',
      'उनके सप्लायर कॉन्टैक्ट्स',
    ],
    1,
  ),
  trivia(
    14,
    'What made Zerodha different from traditional brokers?',
    'Zerodha को पारंपरिक ब्रोकरों से अलग किस बात ने बनाया?',
    [
      'Free stocks for life',
      'A flat, low fee instead of % commission',
      'Phone-call-only trading',
      'Only for big investors',
    ],
    [
      'जीवनभर के लिए मुफ्त स्टॉक्स',
      '% कमीशन की जगह एक फ्लैट, कम फीस',
      'सिर्फ फोन-कॉल से ट्रेडिंग',
      'सिर्फ बड़े निवेशकों के लिए',
    ],
    1,
  ),
  trivia(
    15,
    "Meesho's early growth engine, before big ad budgets, was:",
    'बड़े विज्ञापन बजट से पहले, Meesho की शुरुआती ग्रोथ का ज़रिया था:',
    [
      'TV commercials',
      'WhatsApp & social selling by home resellers',
      'Newspaper ads',
      'Mall kiosks',
    ],
    [
      'TV विज्ञापन',
      'घर से बेचने वालों की WhatsApp और सोशल सेलिंग',
      'अखबार के विज्ञापन',
      'मॉल के कियोस्क',
    ],
    1,
  ),
  trivia(
    16,
    'A UPI transaction mostly costs the customer:',
    'एक UPI ट्रांज़ैक्शन का ग्राहक को आमतौर पर खर्च होता है:',
    ['A flat ₹10 fee', 'Nothing', '2% of the amount', 'A monthly fee'],
    ['एक फ्लैट ₹10 फीस', 'कुछ नहीं', 'राशि का 2%', 'एक मासिक फीस'],
    1,
  ),
  trivia(
    17,
    'GST digitization pushed many wholesalers toward:',
    'GST डिजिटाइज़ेशन ने कई थोक व्यापारियों को किस ओर धकेला:',
    [
      'Better shop interiors',
      'Digital, compliant billing',
      'Bigger warehouses',
      'Franchise models',
    ],
    [
      'बेहतर दुकान की सजावट',
      'डिजिटल, नियम-अनुरूप बिलिंग',
      'बड़े गोदाम',
      'फ्रैंचाइज़ी मॉडल',
    ],
    1,
  ),
  trivia(
    18,
    'The real reason small shops adopt apps like Khatabook is:',
    'छोटी दुकानें Khatabook जैसे ऐप अपनाने की असली वजह है:',
    [
      'It looks modern',
      'It saves hours & reduces payment delays',
      "It's legally required",
      'Competitors forced them',
    ],
    [
      'यह मॉडर्न दिखता है',
      'इससे घंटों की बचत होती है और पेमेंट में देरी कम होती है',
      'यह कानूनी रूप से ज़रूरी है',
      'प्रतिस्पर्धियों ने मजबूर किया',
    ],
    1,
  ),
  trivia(
    19,
    '"Digital-first" mainly means a business:',
    '"डिजिटल-फर्स्ट" का मुख्य मतलब है कि एक बिज़नेस:',
    [
      'Only ever sells online',
      'Builds its processes around tech from day one',
      'Has an Instagram page',
      'Uses computers instead of paper',
    ],
    [
      'सिर्फ ऑनलाइन ही बेचता है',
      'शुरुआत से ही अपनी प्रक्रियाएँ तकनीक के इर्द-गिर्द बनाता है',
      'एक Instagram पेज रखता है',
      'कागज़ की जगह कंप्यूटर इस्तेमाल करता है',
    ],
    1,
  ),
  trivia(
    20,
    'The biggest risk of skipping digital payments today is:',
    'आज डिजिटल पेमेंट न अपनाने का सबसे बड़ा जोखिम है:',
    [
      "Losing UPI-only customers who won't carry cash",
      'Nothing, cash still works everywhere',
      'Extra tax',
      'Losing your shop licence',
    ],
    [
      'सिर्फ UPI इस्तेमाल करने वाले ग्राहकों को खोना, जो कैश नहीं रखते',
      'कुछ नहीं, कैश आज भी हर जगह चलता है',
      'अतिरिक्त टैक्स',
      'दुकान का लाइसेंस खोना',
    ],
    0,
  ),

  // Set C — Company & App Milestones
  trivia(
    21,
    'Zerodha\'s app "Kite" helped the company cross this yearly revenue mark:',
    'Zerodha के ऐप "Kite" ने कंपनी को इस सालाना रेवेन्यू के पार पहुँचाया:',
    ['₹900 crore', '₹9,000+ crore', '₹90 crore', '₹90,000 crore'],
    ['₹900 करोड़', '₹9,000+ करोड़', '₹90 करोड़', '₹90,000 करोड़'],
    1,
  ),
  trivia(
    22,
    'Meesho, a 2015 WhatsApp reselling idea, is now:',
    'Meesho, जो 2015 में एक WhatsApp रीसेलिंग आइडिया था, अब है:',
    [
      'Still a tiny startup',
      "Listed on India's stock exchanges (NSE & BSE)",
      'Shut down',
      'Only a B2B app',
    ],
    [
      'अभी भी एक छोटा सा स्टार्टअप',
      'भारत के स्टॉक एक्सचेंजों (NSE और BSE) पर लिस्टेड',
      'बंद हो चुका',
      'सिर्फ एक B2B ऐप',
    ],
    1,
  ),
  trivia(
    23,
    'Khatabook, the digital ledger app for kirana stores, has crossed:',
    'किराना दुकानों के लिए डिजिटल लेजर ऐप Khatabook ने पार किया है:',
    [
      '5,000 downloads',
      '50 million+ downloads',
      '5 lakh downloads',
      '5 crore paid users',
    ],
    [
      '5,000 डाउनलोड्स',
      '5 करोड़+ (50 मिलियन+) डाउनलोड्स',
      '5 लाख डाउनलोड्स',
      '5 करोड़ पेड यूज़र्स',
    ],
    1,
  ),
  trivia(
    24,
    "India's UPI system now processes billions of transactions:",
    'भारत का UPI सिस्टम अब अरबों ट्रांज़ैक्शन प्रोसेस करता है:',
    ['Every year', 'Every single month', 'Every decade', 'Only on festivals'],
    ['हर साल', 'हर महीने', 'हर दशक में', 'सिर्फ त्योहारों पर'],
    1,
  ),
  trivia(
    25,
    'Which Indian-origin SaaS company serves global customers from India?',
    'कौन सी भारतीय मूल की SaaS कंपनी भारत से दुनिया भर के ग्राहकों को सेवा देती है?',
    ['Zoho', 'Only Silicon Valley firms do this', 'Reliance Jio', 'DMart'],
    [
      'Zoho',
      'यह सिर्फ सिलिकॉन वैली की कंपनियां करती हैं',
      'Reliance Jio',
      'DMart',
    ],
    0,
  ),
  trivia(
    26,
    'boAt became a top audio/wearable brand by focusing early on:',
    'boAt एक टॉप ऑडियो/वियरेबल ब्रांड बना, शुरुआत में इस पर फोकस करके:',
    [
      'TV-only ads',
      'D2C online sales + social media',
      'Mall stores only',
      'Government tenders',
    ],
    [
      'सिर्फ TV विज्ञापन',
      'D2C ऑनलाइन बिक्री + सोशल मीडिया',
      'सिर्फ मॉल स्टोर्स',
      'सरकारी टेंडर',
    ],
    1,
  ),
  trivia(
    27,
    'CRED built its business by rewarding users for:',
    'CRED ने यूज़र्स को इसके लिए इनाम देकर अपना बिज़नेस बनाया:',
    [
      'Opening a bank account',
      'Paying credit card bills on time',
      'Watching ads',
      'Referring 10 friends',
    ],
    [
      'बैंक अकाउंट खोलने पर',
      'समय पर क्रेडिट कार्ड बिल भरने पर',
      'विज्ञापन देखने पर',
      '10 दोस्तों को रेफर करने पर',
    ],
    1,
  ),
  trivia(
    28,
    'Physics Wallah went from free YouTube videos to:',
    'Physics Wallah मुफ्त YouTube वीडियो से बनकर पहुँचा:',
    [
      'A shut-down channel',
      'A billion-dollar ed-tech company',
      'A TV channel only',
      'A print-only publisher',
    ],
    [
      'एक बंद हो चुका चैनल',
      'एक बिलियन-डॉलर एडटेक कंपनी',
      'सिर्फ एक TV चैनल',
      'सिर्फ एक प्रिंट प्रकाशक',
    ],
    1,
  ),
  trivia(
    29,
    'Razorpay grew by solving online payments specifically for:',
    'Razorpay ने खासतौर पर इनके लिए ऑनलाइन पेमेंट की समस्या सुलझाकर तरक्की की:',
    [
      'Only large enterprises',
      'Startups & small businesses banks ignored',
      'Government offices',
      'International tourists',
    ],
    [
      'सिर्फ बड़ी कंपनियों के लिए',
      'स्टार्टअप्स और छोटे बिज़नेस, जिन्हें बैंकों ने नज़रअंदाज़ किया',
      'सरकारी दफ्तरों के लिए',
      'विदेशी पर्यटकों के लिए',
    ],
    1,
  ),
  trivia(
    30,
    'Urban Company turned unorganized home services into:',
    'Urban Company ने असंगठित घरेलू सेवाओं को बदल दिया:',
    [
      'A pamphlet business',
      'A rated, on-demand booking app',
      'A government scheme',
      'A franchise-only model',
    ],
    [
      'एक पर्चे वाला बिज़नेस',
      'एक रेटिंग वाली, ऑन-डिमांड बुकिंग ऐप',
      'एक सरकारी योजना',
      'सिर्फ फ्रैंचाइज़ी मॉडल',
    ],
    1,
  ),

  // Set D — Traditional Business → Digital Transformation
  trivia(
    31,
    'A tailor taking orders & measurements via WhatsApp is:',
    'एक दर्ज़ी जो WhatsApp से ऑर्डर और नाप लेता है, वह:',
    [
      'Doing nothing new',
      'Digitizing customer intake',
      'Losing customers',
      'Breaking a rule',
    ],
    [
      'कुछ नया नहीं कर रहा',
      'ग्राहक जुड़ाव को डिजिटल बना रहा है',
      'ग्राहक खो रहा है',
      'कोई नियम तोड़ रहा है',
    ],
    1,
  ),
  trivia(
    32,
    'A kirana store adding a QR code at the counter mainly solves for:',
    'काउंटर पर QR कोड लगाने वाली किराना दुकान मुख्य रूप से इसका समाधान करती है:',
    [
      'Decoration',
      'Faster, cashless checkout',
      'Free advertising',
      'Tax evasion',
    ],
    ['सजावट', 'तेज़, कैशलेस चेकआउट', 'मुफ्त विज्ञापन', 'टैक्स चोरी'],
    1,
  ),
  trivia(
    33,
    'A manufacturer using WhatsApp Business + Google listing improves:',
    'WhatsApp Business + Google लिस्टिंग इस्तेमाल करने वाला निर्माता किसमें सुधार करता है:',
    [
      'Factory floor space',
      'Customer discovery & communication',
      'Raw material cost',
      'Nothing measurable',
    ],
    [
      'फैक्ट्री की जगह',
      'ग्राहकों तक पहुँच और संवाद',
      'कच्चे माल की लागत',
      'कुछ भी मापने लायक नहीं',
    ],
    1,
  ),
  trivia(
    34,
    'A wholesaler switching to GST-compliant digital billing usually gains:',
    'GST-अनुरूप डिजिटल बिलिंग अपनाने वाले थोक व्यापारी को आमतौर पर मिलता है:',
    [
      'Lower quality stock',
      'Access to bigger, compliant buyers',
      'More paperwork only',
      'No real benefit',
    ],
    [
      'कम गुणवत्ता वाला स्टॉक',
      'बड़े, नियम-अनुरूप खरीदारों तक पहुँच',
      'सिर्फ ज़्यादा कागज़ी काम',
      'कोई असली फायदा नहीं',
    ],
    1,
  ),
  trivia(
    35,
    'A shop using Google Maps + reviews instead of only walk-ins is:',
    'सिर्फ वॉक-इन ग्राहकों के बजाय Google Maps + रिव्यू इस्तेमाल करने वाली दुकान:',
    [
      'Wasting time',
      'Expanding how new customers find them',
      'Risking reputation',
      'Breaking a rule',
    ],
    [
      'समय बर्बाद कर रही है',
      'नए ग्राहकों तक पहुँचने के तरीके बढ़ा रही है',
      'अपनी साख को जोखिम में डाल रही है',
      'कोई नियम तोड़ रही है',
    ],
    1,
  ),
  trivia(
    36,
    'A small business taking orders via Instagram/WhatsApp is really:',
    'Instagram/WhatsApp से ऑर्डर लेने वाला छोटा बिज़नेस असल में:',
    [
      'Doing nothing serious',
      'Turning a social page into a sales channel',
      'Just posting photos',
      'Copying big brands for no reason',
    ],
    [
      'कुछ गंभीर नहीं कर रहा',
      'एक सोशल पेज को सेल्स चैनल में बदल रहा है',
      'सिर्फ फोटो पोस्ट कर रहा है',
      'बिना वजह बड़े ब्रांड्स की नकल कर रहा है',
    ],
    1,
  ),
  trivia(
    37,
    'Why do many small businesses hesitate to adopt tech, even when it helps?',
    'मदद करने के बावजूद कई छोटे बिज़नेस तकनीक अपनाने में क्यों हिचकिचाते हैं?',
    [
      "It's always too expensive",
      'Fear of the unknown / "too complicated for me"',
      "It's illegal without a licence",
      "Tech doesn't actually help small business",
    ],
    [
      'यह हमेशा बहुत महंगी होती है',
      'अनजान चीज़ों का डर / "मेरे लिए बहुत मुश्किल है"',
      'बिना लाइसेंस के यह गैरकानूनी है',
      'तकनीक से छोटे बिज़नेस को असल में कोई फायदा नहीं होता',
    ],
    1,
  ),
  trivia(
    38,
    'A shop using a digital ledger app instead of paper mainly gains:',
    'कागज़ की जगह डिजिटल लेजर ऐप इस्तेमाल करने वाली दुकान को मुख्य रूप से मिलता है:',
    [
      'A nicer-looking register',
      'Faster collections, fewer errors, reminders',
      'Free products',
      'No real change',
    ],
    [
      'एक बेहतर दिखने वाला रजिस्टर',
      'तेज़ वसूली, कम गलतियाँ, रिमाइंडर',
      'मुफ्त प्रोडक्ट्स',
      'कोई असली बदलाव नहीं',
    ],
    1,
  ),
  trivia(
    39,
    'What usually happens to a business that resists digital payments as customers shift to UPI?',
    'जब ग्राहक UPI की ओर बढ़ते हैं, तो डिजिटल पेमेंट न अपनाने वाले बिज़नेस के साथ आमतौर पर क्या होता है?',
    [
      'Nothing changes',
      'It slowly loses digital-first customers',
      'It automatically gets more customers',
      'The government shuts it down',
    ],
    [
      'कुछ नहीं बदलता',
      'वह धीरे-धीरे डिजिटल-फर्स्ट ग्राहकों को खो देता है',
      'उसे अपने आप ज़्यादा ग्राहक मिल जाते हैं',
      'सरकार उसे बंद कर देती है',
    ],
    1,
  ),
  trivia(
    40,
    "The real lesson from Kodak's downfall was:",
    'Kodak के पतन से असली सीख यह मिली:',
    [
      'Cameras became unpopular',
      "They had the tech but didn't commit to adopting it",
      'Film photography became illegal',
      'They ran out of money suddenly',
    ],
    [
      'कैमरे अलोकप्रिय हो गए',
      'उनके पास तकनीक थी पर उसे अपनाने की प्रतिबद्धता नहीं थी',
      'फिल्म फोटोग्राफी गैरकानूनी हो गई',
      'उनके पास अचानक पैसे खत्म हो गए',
    ],
    1,
  ),

  // Set E — General Tech & Digital India Awareness
  trivia(
    41,
    'UPI stands for:',
    'UPI का पूरा नाम है:',
    [
      'Universal Payment Interface',
      'Unified Payments Interface',
      'United Public Investment',
      'Unique Personal ID',
    ],
    [
      'Universal Payment Interface',
      'Unified Payments Interface',
      'United Public Investment',
      'Unique Personal ID',
    ],
    1,
  ),
  trivia(
    42,
    "India's UPI system is built and run by:",
    'भारत का UPI सिस्टम किसके द्वारा बनाया और चलाया जाता है:',
    [
      'A private US company',
      'NPCI (National Payments Corporation of India)',
      'A state government',
      'A private bank alone',
    ],
    [
      'एक निजी अमेरिकी कंपनी',
      'NPCI (नेशनल पेमेंट्स कॉर्पोरेशन ऑफ इंडिया)',
      'एक राज्य सरकार',
      'सिर्फ एक निजी बैंक',
    ],
    1,
  ),
  trivia(
    43,
    '"Digital India" as a national push mainly aims to:',
    '"डिजिटल इंडिया" राष्ट्रीय पहल का मुख्य लक्ष्य है:',
    [
      'Ban cash completely',
      'Bring government services & the economy online for everyone',
      'Only help big cities',
      'Replace all shops with apps',
    ],
    [
      'कैश को पूरी तरह बैन करना',
      'सरकारी सेवाओं और अर्थव्यवस्था को सबके लिए ऑनलाइन लाना',
      'सिर्फ बड़े शहरों की मदद करना',
      'सभी दुकानों को ऐप्स से बदल देना',
    ],
    1,
  ),
  trivia(
    44,
    'Aadhaar-based digital identity mainly helps businesses by:',
    'आधार-आधारित डिजिटल पहचान बिज़नेस की मुख्य रूप से मदद करती है:',
    [
      'Enabling faster, paperless verification',
      "Nothing, it's only for individuals",
      'Increasing paperwork',
      'Replacing GST',
    ],
    [
      'तेज़, कागज़-रहित वेरिफिकेशन में',
      'कुछ नहीं, यह सिर्फ व्यक्तियों के लिए है',
      'कागज़ी काम बढ़ाकर',
      'GST की जगह लेकर',
    ],
    0,
  ),
  trivia(
    45,
    'A QR code on a shop counter works because it:',
    'दुकान के काउंटर पर QR कोड इसलिए काम करता है क्योंकि यह:',
    [
      'Needs special hardware',
      'Links straight to a payment app on any smartphone',
      'Only works with one bank',
      "Needs internet only on the customer's side",
    ],
    [
      'खास हार्डवेयर की ज़रूरत रखता है',
      'किसी भी स्मार्टफोन पर सीधे पेमेंट ऐप से जुड़ जाता है',
      'सिर्फ एक बैंक के साथ काम करता है',
      'सिर्फ ग्राहक की तरफ इंटरनेट चाहिए',
    ],
    1,
  ),
  trivia(
    46,
    'E-commerce in India grew fastest after:',
    'भारत में ई-कॉमर्स सबसे तेज़ी से बढ़ा जब:',
    [
      'Smartphones & cheap data became widely available',
      'Newspapers increased ads',
      'Shops started closing early',
      'Nothing changed',
    ],
    [
      'स्मार्टफोन और सस्ता डेटा आम हो गए',
      'अखबारों ने विज्ञापन बढ़ाए',
      'दुकानें जल्दी बंद होने लगीं',
      'कुछ नहीं बदला',
    ],
    0,
  ),
  trivia(
    47,
    '"Google My Business" listing mainly helps with:',
    '"Google My Business" लिस्टिंग मुख्य रूप से इसमें मदद करती है:',
    [
      'Filing taxes',
      'Being found by nearby customers searching online',
      'Paying employees',
      'Managing inventory',
    ],
    [
      'टैक्स फाइल करने में',
      'आस-पास ऑनलाइन खोज रहे ग्राहकों तक मिलने में',
      'कर्मचारियों को भुगतान करने में',
      'इन्वेंटरी मैनेज करने में',
    ],
    1,
  ),
  trivia(
    48,
    'WhatsApp Business (different from regular WhatsApp) gives small businesses:',
    'WhatsApp Business (सामान्य WhatsApp से अलग) छोटे बिज़नेस को देता है:',
    [
      'Free Instagram ads',
      'Catalogs, auto-replies & business profiles',
      'A physical store',
      'Free delivery staff',
    ],
    [
      'मुफ्त Instagram विज्ञापन',
      'कैटलॉग, ऑटो-रिप्लाई और बिज़नेस प्रोफाइल',
      'एक फिजिकल स्टोर',
      'मुफ्त डिलीवरी स्टाफ',
    ],
    1,
  ),
  trivia(
    49,
    'Cloud-based business tools mainly help small businesses by:',
    'क्लाउड-आधारित बिज़नेस टूल्स छोटे बिज़नेस की मुख्य रूप से मदद करते हैं:',
    [
      'Needing a huge upfront computer setup',
      'Letting them access data from anywhere, anytime',
      'Working only in one shop',
      'Making data less safe',
    ],
    [
      'एक बड़े शुरुआती कंप्यूटर सेटअप की ज़रूरत डालकर',
      'उन्हें कहीं से भी, कभी भी डेटा एक्सेस करने देकर',
      'सिर्फ एक दुकान में काम करके',
      'डेटा को कम सुरक्षित बनाकर',
    ],
    1,
  ),
  trivia(
    50,
    'The single biggest reason small businesses are told to "go digital" today is:',
    'आज छोटे बिज़नेस को "डिजिटल बनो" कहने की सबसे बड़ी वजह है:',
    [
      "It's mandatory now",
      'Customers themselves have already gone digital first',
      'Government forces it',
      'It has no real business impact',
    ],
    [
      'अब यह अनिवार्य है',
      'ग्राहक खुद पहले ही डिजिटल-फर्स्ट हो चुके हैं',
      'सरकार इसे मजबूर करती है',
      'इसका बिज़नेस पर कोई असली असर नहीं',
    ],
    1,
  ),
];
